INSERT INTO resi18nresource(applicationname,
                            languagecode,
                            resourcekey,
                            resourcevalue,
                            createddate,
                            createdby,
                            modifieddate,
                            modifiedby)
VALUES     ('omnibilling',
            'zh-cn',
            'MsBillingErrorCode.CONFIG_FOR_ALL_USER_EXIST',
            '存在适用所有用户的计费配置，请修改(计费项、资源、计费目标类型)中任意一项，对未配置的(计费项、资源、计费目标类型)进行配置。 %s',
            Now(),
            '-99999',
            Now(),
            '-99999');

INSERT INTO resi18nresource(applicationname,
                            languagecode,
                            resourcekey,
                            resourcevalue,
                            createddate,
                            createdby,
                            modifieddate,
                            modifiedby)
VALUES     ('omnibilling',
            'en-us',
            'MsBillingErrorCode.CONFIG_FOR_ALL_USER_EXIST',
            'config for all user exist.please modify anyone of(billingItem,resource,billingTargetType),config for(billingItem,resource,billingTargetType) which has not been configured yet.%s',
            Now(),
            '-99999',
            Now(),
            '-99999');

INSERT INTO resi18nresource(applicationname,
                            languagecode,
                            resourcekey,
                            resourcevalue,
                            createddate,
                            createdby,
                            modifieddate,
                            modifiedby)
VALUES     ('omnibilling',
            'pl-pl',
            'MsBillingErrorCode.CONFIG_FOR_ALL_USER_EXIST',
            'config for all user exist.please modify anyone of(billingItem,resource,billingTargetType),config for(billingItem,resource,billingTargetType) which has not been configured yet.%s',
            Now(),
            '-99999',
            Now(),
            '-99999');

INSERT INTO resi18nresource(applicationname,
                            languagecode,
                            resourcekey,
                            resourcevalue,
                            createddate,
                            createdby,
                            modifieddate,
                            modifiedby)
VALUES     ('omnibilling',
            'zh-cn',
            'MsBillingErrorCode.CONFIG_FOR_CURRENT_USER_EXIST',
            '用户已存在该计费配置，请修改(计费项、资源、计费目标类型)中任意一项或移除原有用户，对未配置的(计费项、资源、计费目标类型以及用户)进行配置。 %s',
            Now(),
            '-99999',
            Now(),
            '-99999');

INSERT INTO resi18nresource(applicationname,
                            languagecode,
                            resourcekey,
                            resourcevalue,
                            createddate,
                            createdby,
                            modifieddate,
                            modifiedby)
VALUES     ('omnibilling',
            'en-us',
            'MsBillingErrorCode.CONFIG_FOR_CURRENT_USER_EXIST',
            'config for user exist.please modify anyone of(billingItem,resource,billingTargetType) or remove user has been configured,config for(billingItem,resource,billingTargetType and user) which has not been configured yet. %s',
            Now(),
            '-99999',
            Now(),
            '-99999');

INSERT INTO resi18nresource(applicationname,
                            languagecode,
                            resourcekey,
                            resourcevalue,
                            createddate,
                            createdby,
                            modifieddate,
                            modifiedby)
VALUES     ('omnibilling',
            'pl-pl',
            'MsBillingErrorCode.CONFIG_FOR_CURRENT_USER_EXIST',
            'config for user exist.please modify anyone of(billingItem,resource,billingTargetType) or remove user has been configured,config for(billingItem,resource,billingTargetType and user) which has not been configured yet. %s',
            Now(),
            '-99999',
            Now(),
            '-99999');