INSERT INTO `omniv4`.`fieldspec` (`objectClass`, `fieldSpecName`, `sysFieldFlag`, `groupId`, `labelI18n`, `defaultValue`, `dataType`, `requiredFlag`, `formatterInfo`, `patternInfo`, `tipInfo`, `enumFlag`, `maxLength`, `minVal`, `maxVal`, `calculateImplClass`, `calculatedFieldCriteriaClass`, `multipleFlag`, `createdDate`, `createdBy`, `modifiedDate`, `modifiedBy`) VALUES ('com.omniselling.channel.omnicart.OmniCartCredential', 'ocCustomerEmail', '0', NULL, 'OmniCartCredential.ocCustomerEmail', NULL, 'String', '0', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NOW(), '-99999', NOW(), '-99999');
INSERT INTO `omniv4`.`fieldspec` (`objectClass`, `fieldSpecName`, `sysFieldFlag`, `groupId`, `labelI18n`, `defaultValue`, `dataType`, `requiredFlag`, `formatterInfo`, `patternInfo`, `tipInfo`, `enumFlag`, `maxLength`, `minVal`, `maxVal`, `calculateImplClass`, `calculatedFieldCriteriaClass`, `multipleFlag`, `createdDate`, `createdBy`, `modifiedDate`, `modifiedBy`) VALUES ('com.omniselling.channel.omnicart.OmniCartConfigure', 'isActiveWriteBack', '0', NULL, 'OmniCartConfigure.isActiveWriteBack', '0', 'Boolean', '1', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NOW(), '-99999', NOW(), '-99999');
INSERT INTO `omniv4`.`fieldspec` (`objectClass`, `fieldSpecName`, `sysFieldFlag`, `groupId`, `labelI18n`, `defaultValue`, `dataType`, `requiredFlag`, `formatterInfo`, `patternInfo`, `tipInfo`, `enumFlag`, `maxLength`, `minVal`, `maxVal`, `calculateImplClass`, `calculatedFieldCriteriaClass`, `multipleFlag`, `createdDate`, `createdBy`, `modifiedDate`, `modifiedBy`) VALUES ('com.omniselling.channel.omnicart.OmniCartCredential', 'isB2bAccount', '0', NULL, 'OmniCartCredential.isB2bAccount', '0', 'Boolean', '1', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NOW(), '-99999', NOW(), '-99999');
INSERT INTO `omniv4`.`fieldspec` (`objectClass`, `fieldSpecName`, `sysFieldFlag`, `groupId`, `labelI18n`, `defaultValue`, `dataType`, `requiredFlag`, `formatterInfo`, `patternInfo`, `tipInfo`, `enumFlag`, `maxLength`, `minVal`, `maxVal`, `calculateImplClass`, `calculatedFieldCriteriaClass`, `multipleFlag`, `createdDate`, `createdBy`, `modifiedDate`, `modifiedBy`) VALUES ('com.omniselling.channel.omnicart.OmniCartCredential', 'writeBackDate', '0', NULL, 'OmniCartCredential.writeBackDate', NULL, 'String', '0', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NOW(), '-99999', NOW(), '-99999');
INSERT INTO `omniv4`.`fieldspec` (`objectClass`, `fieldSpecName`, `sysFieldFlag`, `groupId`, `labelI18n`, `defaultValue`, `dataType`, `requiredFlag`, `formatterInfo`, `patternInfo`, `tipInfo`, `enumFlag`, `maxLength`, `minVal`, `maxVal`, `calculateImplClass`, `calculatedFieldCriteriaClass`, `multipleFlag`, `createdDate`, `createdBy`, `modifiedDate`, `modifiedBy`) VALUES ('com.omniselling.channel.omnicart.OmniCartCredential', 'ocCustomerId', '0', NULL, 'OmniCartCredential.ocCustomerId', NULL, 'String', '0', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NOW(), '-99999', NOW(), '-99999');







